### ISSUE TITLE
Do not forward ports outside of the container

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate-hass-addons#66]
The default configuration is currently:

https://github.com/blakeblackshear/frigate-hass-addons/blob/b48a1d7484c5dfd1b10b3d6b5a9573bfd3e9b272/frigate/config.yaml#L16-L18

I wonder if we should not change it to:

```yaml
ports:
  5000/tcp: null
  1935/tcp: null
```

Considering that they are not needed for using with the Home Assistant integration or the ingress side panel.

Advanced users who would like to have them exposed outside of the Home Assistant for whatever reason could simply enable it back.

**Comment by protoEvangelion** [comment]
Well I think you got your wish but my sadness because I'm not able to set leverage the api for notifications.

IE as the docs suggest something like: https://docs.frigate.video/guides/ha_notifications/

```
192.168.1.1:5000/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
```

Looks like code has already been updated to exactly what you are suggesting: https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate/config.yaml#L17

**Comment by felipecrs** [comment]
There is no need to access Frigate's endpoint to access the Frigate API within HA because the Frigate HA Integration proxies it for you.

@NickM-27, @dermotduffy please correct me if I'm wrong.

**Comment by felipecrs** [comment]
> Looks like code has already been updated to exactly what you are suggesting: https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate/config.yaml#L17

That's true. Thanks for the heads up.
